spring:
  application:
    name: ${SPRING_APPLICATION_NAME:library-management-service}
  webflux:
    basePath: /library-management-service
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://root:password@mongodb_container:27017/library-management?authSource=admin
      port: 27017
      database: library-management

management:
  server:
    port: 9089
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus, beans
  endpoint:
    health:
      show-details: always

logging:
  level:
    my:
      cld:
        library: TRACE
      zalando:
        logbook: TRACE

server:
  port: 8089

logbook:
  include:
    - /**
  exclude:
    - /actuator/**
    - ${spring.webflux.basePath}/webjars/**
    - ${spring.webflux.basePath}/v3/api-docs/**
    - ${spring.webflux.basePath}/swagger-ui.html/**
    - ${spring.webflux.basePath}/swagger-resources/**
  filter.enabled: true
  format.style: splunk
  strategy: default
  obfuscate:
    parameters:
      - access_token
      - password
      - token

springdoc:
  swagger-ui:
    enable: true