apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_DATABASE: bGlicmFyeQ==    # Base64 encoded 'library'
  MONGO_USER: YWRtaW4=            # Base64 encoded 'admin'
  MONGO_PASSWORD: cGFzc3dvcmQ=    # Base64 encoded 'password'
